"use client";

import { useState, useEffect, useCallback, useMemo, useRef } from "react";
import { toast } from "@/components/ui/sonner";
import type {
  FinancialTransaction,
  ServiceFormValues,
  PaginatedResponse,
} from "../shared/finance-types";
import { calculateSMM } from "../muhasebe-ucretleri/smm-calculator";

interface UseServicesParams {
  customerId?: string;
  categoryId?: string;
  status?: string;
  startDate?: string;
  endDate?: string;
}

export function useServices(params?: UseServicesParams) {
  const [services, setServices] = useState<FinancialTransaction[]>([]);
  const [total, setTotal] = useState(0);
  const [loading, setLoading] = useState(true);
  const abortRef = useRef<AbortController | null>(null);

  const fetchServices = useCallback(
    async (overrideParams?: UseServicesParams) => {
      abortRef.current?.abort();
      const controller = new AbortController();
      abortRef.current = controller;

      try {
        setLoading(true);
        const p = overrideParams || params;
        const searchParams = new URLSearchParams();
        searchParams.set("type", "DEBIT");
        searchParams.set("autoGenerated", "false");
        searchParams.set("hasCostDefinition", "false");

        if (p?.customerId) searchParams.set("customerId", p.customerId);
        if (p?.categoryId) searchParams.set("categoryId", p.categoryId);
        if (p?.status) searchParams.set("status", p.status);
        if (p?.startDate) searchParams.set("startDate", p.startDate);
        if (p?.endDate) searchParams.set("endDate", p.endDate);
        searchParams.set("limit", "200");

        const url = `/api/finance/transactions?${searchParams.toString()}`;
        const res = await fetch(url, { signal: controller.signal });
        if (controller.signal.aborted) return;
        if (!res.ok) throw new Error("Hizmetler yüklenemedi");
        const data = await res.json();

        if (Array.isArray(data)) {
          setServices(data);
          setTotal(data.length);
        } else {
          const paginated = data as PaginatedResponse<FinancialTransaction>;
          setServices(paginated.data);
          setTotal(paginated.total);
        }
      } catch (error) {
        if (error instanceof DOMException && error.name === "AbortError")
          return;
        console.error("Hizmet yükleme hatası:", error);
        toast.error("Hizmetler yüklenirken hata oluştu");
      } finally {
        if (!controller.signal.aborted) setLoading(false);
      }
    },
    [
      params?.customerId,
      params?.categoryId,
      params?.status,
      params?.startDate,
      params?.endDate,
    ]
  );

  useEffect(() => {
    fetchServices();
    return () => abortRef.current?.abort();
  }, [fetchServices]);

  const createService = useCallback(async (data: ServiceFormValues) => {
    const smm = calculateSMM(
      data.amount,
      data.kdvRate || 0,
      data.stopajRate || 0,
      data.hasSMM
    );

    const payload = {
      customerId: data.customerId,
      categoryId: data.categoryId,
      type: "DEBIT" as const,
      amount: data.amount,
      currency: data.currency,
      grossAmount: smm.grossAmount,
      kdvAmount: smm.kdvAmount,
      stopajAmount: smm.stopajAmount,
      netAmount: smm.netAmount,
      date: data.date,
      dueDate: data.dueDate || null,
      description: data.description || null,
      status: "PENDING" as const,
      autoGenerated: false,
      costDefinitionId: null,
    };

    const res = await fetch("/api/finance/transactions", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(payload),
    });
    if (!res.ok) {
      const err = await res.json().catch(() => ({}));
      throw new Error(err.error || "Hizmet oluşturulamadı");
    }
    const created = await res.json();
    setServices((prev) => [created, ...prev]);
    return created as FinancialTransaction;
  }, []);

  const updateService = useCallback(
    async (id: string, data: ServiceFormValues) => {
      const smm = calculateSMM(
        data.amount,
        data.kdvRate || 0,
        data.stopajRate || 0,
        data.hasSMM
      );

      const payload = {
        customerId: data.customerId,
        categoryId: data.categoryId,
        amount: data.amount,
        currency: data.currency,
        grossAmount: smm.grossAmount,
        kdvAmount: smm.kdvAmount,
        stopajAmount: smm.stopajAmount,
        netAmount: smm.netAmount,
        date: data.date,
        dueDate: data.dueDate || null,
        description: data.description || null,
      };

      const res = await fetch(`/api/finance/transactions/${id}`, {
        method: "PUT",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(payload),
      });
      if (!res.ok) {
        const err = await res.json().catch(() => ({}));
        throw new Error(err.error || "Hizmet güncellenemedi");
      }
      const updated = await res.json();
      setServices((prev) => prev.map((s) => (s.id === id ? updated : s)));
      return updated as FinancialTransaction;
    },
    []
  );

  const deleteService = useCallback(async (id: string) => {
    const res = await fetch(`/api/finance/transactions/${id}`, {
      method: "DELETE",
    });
    if (!res.ok) {
      const err = await res.json().catch(() => ({}));
      throw new Error(err.error || "Hizmet iptal edilemedi");
    }
    setServices((prev) => prev.filter((s) => s.id !== id));
  }, []);

  const summaryStats = useMemo(() => {
    const now = new Date();
    const startOfMonth = new Date(now.getFullYear(), now.getMonth(), 1);
    const endOfMonth = new Date(now.getFullYear(), now.getMonth() + 1, 0);

    let pendingTotal = 0;
    let thisMonthTotal = 0;

    for (const s of services) {
      if (s.status === "PENDING" || s.status === "PARTIAL") {
        pendingTotal += Number(s.netAmount);
      }
      const sDate = new Date(s.date);
      if (sDate >= startOfMonth && sDate <= endOfMonth) {
        thisMonthTotal += Number(s.netAmount);
      }
    }

    return { pendingTotal, thisMonthTotal, totalCount: services.length };
  }, [services]);

  return {
    services,
    total,
    loading,
    fetchServices,
    createService,
    updateService,
    deleteService,
    summaryStats,
  };
}
