import { NextRequest, NextResponse } from "next/server";
import { prisma } from "@/lib/db";

/**
 * GET /api/cron/auto-charge
 * Vercel Cron Job - Maliyet tanımlarından otomatik borç kayıtları oluştur
 * Günde 1 kez, 04:00 UTC'de çalışır (Türkiye saati 07:00)
 *
 * Her tenant'ın ayarlarındaki autoChargeDay gününde,
 * aktif cost_definitions'lar için DEBIT transaction oluşturur.
 */
export async function GET(req: NextRequest) {
  try {
    // Cron secret kontrolü
    const authHeader = req.headers.get("authorization");
    if (authHeader !== `Bearer ${process.env.CRON_SECRET}`) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }

    const now = new Date();
    const currentDay = now.getUTCDate();
    const currentPeriod = getCurrentPeriod(now);
    console.log(
      `[Cron Auto-Charge] Başlatılıyor: ${now.toISOString()}, Dönem: ${currentPeriod}, Gün: ${currentDay}`
    );

    // Otomatik faturalama açık olan tenant'ları bul
    const tenants = await prisma.tenants.findMany({
      where: {
        financialDefaults: { not: undefined },
      },
      select: { id: true, financialDefaults: true },
    });

    let totalCreated = 0;
    let totalSkipped = 0;
    let totalErrors = 0;

    for (const tenant of tenants) {
      const defaults = (tenant.financialDefaults as Record<string, unknown>) || {};
      const autoChargeEnabled = defaults.autoChargeEnabled === true;
      const autoChargeDay = (defaults.autoChargeDay as number) || 1;

      // Bu tenant için otomatik faturalama kapalı veya bugün faturalama günü değilse atla
      if (!autoChargeEnabled || currentDay !== autoChargeDay) {
        continue;
      }

      console.log(
        `[Cron Auto-Charge] Tenant ${tenant.id} için faturalama başlıyor (gün: ${autoChargeDay})`
      );

      // Bu tenant'ın aktif maliyet tanımlarını getir
      const costDefinitions = await prisma.cost_definitions.findMany({
        where: {
          tenantId: tenant.id,
          isActive: true,
          startDate: { lte: now },
          OR: [{ endDate: null }, { endDate: { gte: now } }],
        },
        include: {
          category: { select: { id: true, name: true } },
          customers: { select: { id: true, unvan: true } },
        },
      });

      for (const def of costDefinitions) {
        try {
          // Frekansa göre bu dönemde oluşturulmalı mı?
          if (!shouldChargeForPeriod(def.frequency, currentPeriod, def.chargeStrategy)) {
            totalSkipped++;
            continue;
          }

          // Bu dönem için zaten log var mı? (duplicate önleme)
          const existingLog = await prisma.auto_charge_logs.findUnique({
            where: {
              costDefinitionId_period: {
                costDefinitionId: def.id,
                period: currentPeriod,
              },
            },
          });

          if (existingLog) {
            totalSkipped++;
            continue;
          }

          // Tutar hesaplama
          const amounts = calculateAmounts(def);

          // Vade tarihi: ayın son günü
          const dueDate = getLastDayOfMonth(now);

          // DEBIT transaction oluştur
          const transaction = await prisma.financial_transactions.create({
            data: {
              customerId: def.customerId,
              costDefinitionId: def.id,
              categoryId: def.categoryId,
              type: "DEBIT",
              amount: amounts.grossAmount,
              grossAmount: amounts.grossAmount,
              kdvAmount: amounts.kdvAmount,
              stopajAmount: amounts.stopajAmount,
              netAmount: amounts.netAmount,
              currency: def.currency,
              description: `${def.category.name} - ${currentPeriod} (Otomatik)`,
              date: now,
              dueDate,
              status: "PENDING",
              autoGenerated: true,
              tenantId: tenant.id,
            },
          });

          // Başarılı log kaydı
          await prisma.auto_charge_logs.create({
            data: {
              costDefinitionId: def.id,
              transactionId: transaction.id,
              period: currentPeriod,
              status: "SUCCESS",
              tenantId: tenant.id,
            },
          });

          totalCreated++;
          console.log(
            `[Cron Auto-Charge] Oluşturuldu: ${def.customers.unvan} - ${def.category.name} - ${amounts.grossAmount} TL (${currentPeriod})`
          );
        } catch (error) {
          totalErrors++;
          console.error(
            `[Cron Auto-Charge] Hata (${def.id} - ${def.customers.unvan}):`,
            error
          );

          // Hata log kaydı
          try {
            await prisma.auto_charge_logs.create({
              data: {
                costDefinitionId: def.id,
                period: currentPeriod,
                status: "FAILED",
                errorMessage:
                  error instanceof Error ? error.message : "Bilinmeyen hata",
                tenantId: tenant.id,
              },
            });
          } catch {
            // Log oluşturma da başarısız olursa sessizce geç
          }
        }
      }
    }

    console.log(
      `[Cron Auto-Charge] Tamamlandı: ${totalCreated} oluşturuldu, ${totalSkipped} atlandı, ${totalErrors} hata`
    );

    return NextResponse.json({
      success: true,
      period: currentPeriod,
      created: totalCreated,
      skipped: totalSkipped,
      errors: totalErrors,
      executedAt: now.toISOString(),
    });
  } catch (error) {
    console.error("[Cron Auto-Charge] Fatal hata:", error);
    return NextResponse.json(
      { error: "Internal server error" },
      { status: 500 }
    );
  }
}

/**
 * Manuel faturalama endpoint'i
 * Belirli bir tenant için tüm aktif maliyet tanımlarını hemen faturalandır
 */
export async function POST(req: NextRequest) {
  try {
    // Cron secret kontrolü
    const authHeader = req.headers.get("authorization");
    if (authHeader !== `Bearer ${process.env.CRON_SECRET}`) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }

    const body = await req.json();
    const { tenantId, period: requestedPeriod } = body;

    if (!tenantId) {
      return NextResponse.json({ error: "tenantId gerekli" }, { status: 400 });
    }

    const now = new Date();
    const period = requestedPeriod || getCurrentPeriod(now);

    const costDefinitions = await prisma.cost_definitions.findMany({
      where: {
        tenantId,
        isActive: true,
        startDate: { lte: now },
        OR: [{ endDate: null }, { endDate: { gte: now } }],
      },
      include: {
        category: { select: { id: true, name: true } },
        customers: { select: { id: true, unvan: true } },
      },
    });

    let created = 0;
    let skipped = 0;
    let errors = 0;

    for (const def of costDefinitions) {
      try {
        if (!shouldChargeForPeriod(def.frequency, period, def.chargeStrategy)) {
          skipped++;
          continue;
        }

        const existingLog = await prisma.auto_charge_logs.findUnique({
          where: {
            costDefinitionId_period: {
              costDefinitionId: def.id,
              period,
            },
          },
        });

        if (existingLog) {
          skipped++;
          continue;
        }

        const amounts = calculateAmounts(def);
        const dueDate = getLastDayOfMonth(now);

        const transaction = await prisma.financial_transactions.create({
          data: {
            customerId: def.customerId,
            costDefinitionId: def.id,
            categoryId: def.categoryId,
            type: "DEBIT",
            amount: amounts.grossAmount,
            grossAmount: amounts.grossAmount,
            kdvAmount: amounts.kdvAmount,
            stopajAmount: amounts.stopajAmount,
            netAmount: amounts.netAmount,
            currency: def.currency,
            description: `${def.category.name} - ${period} (Manuel)`,
            date: now,
            dueDate,
            status: "PENDING",
            autoGenerated: true,
            tenantId,
          },
        });

        await prisma.auto_charge_logs.create({
          data: {
            costDefinitionId: def.id,
            transactionId: transaction.id,
            period,
            status: "SUCCESS",
            tenantId,
          },
        });

        created++;
      } catch (error) {
        errors++;
        try {
          await prisma.auto_charge_logs.create({
            data: {
              costDefinitionId: def.id,
              period,
              status: "FAILED",
              errorMessage:
                error instanceof Error ? error.message : "Bilinmeyen hata",
              tenantId,
            },
          });
        } catch {
          // Sessizce geç
        }
      }
    }

    return NextResponse.json({
      success: true,
      period,
      created,
      skipped,
      errors,
      total: costDefinitions.length,
    });
  } catch (error) {
    console.error("[Auto-Charge Manuel] Fatal hata:", error);
    return NextResponse.json(
      { error: "Internal server error" },
      { status: 500 }
    );
  }
}

// ─── Yardımcı Fonksiyonlar ────────────────────────────────────────────

function getCurrentPeriod(date: Date): string {
  return `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, "0")}`;
}

function shouldChargeForPeriod(
  frequency: string,
  period: string,
  chargeStrategy: string
): boolean {
  const month = parseInt(period.split("-")[1], 10);

  switch (frequency) {
    case "MONTHLY":
      return true;
    case "QUARTERLY":
      // Dağıtılmış ise her ay, değilse çeyrek başları
      if (chargeStrategy === "DISTRIBUTED") return true;
      return [1, 4, 7, 10].includes(month);
    case "BIANNUAL":
      if (chargeStrategy === "DISTRIBUTED") return true;
      return [1, 7].includes(month);
    case "ANNUAL":
      if (chargeStrategy === "DISTRIBUTED") return true;
      return month === 1;
    case "ONE_TIME":
      return false; // Tek seferlik tanımlar cron ile işlenmez
    default:
      return false;
  }
}

function toNum(val: unknown): number {
  if (val == null) return 0;
  if (typeof val === "number") return val;
  if (typeof val === "object" && val !== null && "toNumber" in val) {
    return (val as { toNumber: () => number }).toNumber();
  }
  return Number(val);
}

interface CostDefForCalc {
  amount: unknown;
  hasSMM: boolean;
  kdvRate: unknown;
  stopajRate: unknown;
  frequency: string;
  chargeStrategy: string;
}

function calculateAmounts(def: CostDefForCalc) {
  const baseAmount = toNum(def.amount);

  // Dağıtılmış strateji: yıllık/6 aylık/çeyreklik tutarı aylara böl
  let periodAmount = baseAmount;
  if (def.chargeStrategy === "DISTRIBUTED") {
    switch (def.frequency) {
      case "ANNUAL":
        periodAmount = baseAmount / 12;
        break;
      case "BIANNUAL":
        periodAmount = baseAmount / 6;
        break;
      case "QUARTERLY":
        periodAmount = baseAmount / 3;
        break;
    }
  }

  const kdvRate = def.hasSMM ? toNum(def.kdvRate) : 0;
  const stopajRate = def.hasSMM ? toNum(def.stopajRate) : 0;

  const kdvAmount = periodAmount * (kdvRate / 100);
  const stopajAmount = periodAmount * (stopajRate / 100);
  const grossAmount = periodAmount + kdvAmount;
  const netAmount = periodAmount + kdvAmount - stopajAmount;

  // 2 ondalık basamağa yuvarla
  return {
    grossAmount: Math.round(grossAmount * 100) / 100,
    kdvAmount: Math.round(kdvAmount * 100) / 100,
    stopajAmount: Math.round(stopajAmount * 100) / 100,
    netAmount: Math.round(netAmount * 100) / 100,
  };
}

function getLastDayOfMonth(date: Date): Date {
  return new Date(date.getFullYear(), date.getMonth() + 1, 0);
}
