import { getUserWithProfile } from "@/lib/supabase/auth";
import { prisma } from "@/lib/db";
import { NextRequest, NextResponse } from "next/server";

// Tek işlem getir
export async function GET(
  req: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  try {
    const user = await getUserWithProfile();
    if (!user) {
      return NextResponse.json({ error: "Yetkisiz erişim" }, { status: 401 });
    }

    const { id } = await params;
    const transaction = await prisma.financial_transactions.findFirst({
      where: { id, tenantId: user.tenantId },
      include: {
        customers: { select: { id: true, unvan: true, kisaltma: true, vknTckn: true } },
        category: { select: { id: true, name: true, type: true, color: true } },
        check: true,
        child_transactions: {
          orderBy: { date: "desc" },
        },
      },
    });

    if (!transaction) {
      return NextResponse.json({ error: "İşlem bulunamadı" }, { status: 404 });
    }

    return NextResponse.json(transaction);
  } catch (error) {
    console.error("İşlem getirme hatası:", error);
    return NextResponse.json({ error: "Sunucu hatası" }, { status: 500 });
  }
}

// İşlem güncelle
export async function PUT(
  req: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  try {
    const user = await getUserWithProfile();
    if (!user) {
      return NextResponse.json({ error: "Yetkisiz erişim" }, { status: 401 });
    }

    const { id } = await params;
    const body = await req.json();

    const existing = await prisma.financial_transactions.findFirst({
      where: { id, tenantId: user.tenantId },
    });

    if (!existing) {
      return NextResponse.json({ error: "İşlem bulunamadı" }, { status: 404 });
    }

    // Tamamlanmış işlemler düzenlenemez
    if (existing.status === "COMPLETED") {
      return NextResponse.json(
        { error: "Tamamlanmış işlemler düzenlenemez" },
        { status: 400 }
      );
    }

    // Manuel hizmet işlemleri (autoGenerated=false) için daha fazla alan düzenlenebilir
    const isManualService = !existing.autoGenerated && !existing.costDefinitionId;

    const updateData: Record<string, unknown> = {
      ...(body.description !== undefined && { description: body.description }),
      ...(body.dueDate !== undefined && { dueDate: body.dueDate ? new Date(body.dueDate) : null }),
      ...(body.status !== undefined && { status: body.status }),
    };

    if (isManualService) {
      if (body.categoryId !== undefined) updateData.categoryId = body.categoryId;
      if (body.amount !== undefined) updateData.amount = body.amount;
      if (body.currency !== undefined) updateData.currency = body.currency;
      if (body.grossAmount !== undefined) updateData.grossAmount = body.grossAmount;
      if (body.kdvAmount !== undefined) updateData.kdvAmount = body.kdvAmount;
      if (body.stopajAmount !== undefined) updateData.stopajAmount = body.stopajAmount;
      if (body.netAmount !== undefined) updateData.netAmount = body.netAmount;
      if (body.date !== undefined) updateData.date = new Date(body.date);
      if (body.customerId !== undefined) updateData.customerId = body.customerId;
    }

    const updated = await prisma.financial_transactions.update({
      where: { id },
      data: updateData,
      include: {
        customers: { select: { id: true, unvan: true, kisaltma: true } },
        category: { select: { id: true, name: true, color: true, icon: true } },
      },
    });

    return NextResponse.json(updated);
  } catch (error) {
    console.error("İşlem güncelleme hatası:", error);
    return NextResponse.json({ error: "Sunucu hatası" }, { status: 500 });
  }
}

// İşlem iptal et (soft delete)
export async function DELETE(
  req: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  try {
    const user = await getUserWithProfile();
    if (!user) {
      return NextResponse.json({ error: "Yetkisiz erişim" }, { status: 401 });
    }

    const { id } = await params;
    const existing = await prisma.financial_transactions.findFirst({
      where: { id, tenantId: user.tenantId },
    });

    if (!existing) {
      return NextResponse.json({ error: "İşlem bulunamadı" }, { status: 404 });
    }

    await prisma.financial_transactions.update({
      where: { id },
      data: { status: "CANCELLED" },
    });

    return NextResponse.json({ message: "İşlem iptal edildi" });
  } catch (error) {
    console.error("İşlem iptal hatası:", error);
    return NextResponse.json({ error: "Sunucu hatası" }, { status: 500 });
  }
}
