import { getUserWithProfile } from "@/lib/supabase/auth";
import { prisma } from "@/lib/db";
import { NextRequest, NextResponse } from "next/server";

/**
 * POST /api/finance/auto-charge
 * Manuel faturalama - Kullanıcı butona bastığında aktif maliyet tanımlarından borç oluşturur
 */
export async function POST(req: NextRequest) {
  try {
    const user = await getUserWithProfile();
    if (!user) {
      return NextResponse.json({ error: "Yetkisiz erişim" }, { status: 401 });
    }

    const body = await req.json();
    const { period: requestedPeriod } = body || {};

    const now = new Date();
    const period = requestedPeriod || getCurrentPeriod(now);

    // Aktif maliyet tanımlarını getir
    const costDefinitions = await prisma.cost_definitions.findMany({
      where: {
        tenantId: user.tenantId,
        isActive: true,
        startDate: { lte: now },
        OR: [{ endDate: null }, { endDate: { gte: now } }],
      },
      include: {
        category: { select: { id: true, name: true } },
        customers: { select: { id: true, unvan: true } },
      },
    });

    if (costDefinitions.length === 0) {
      return NextResponse.json({
        success: true,
        message: "Aktif maliyet tanımı bulunamadı",
        created: 0,
        skipped: 0,
        errors: 0,
      });
    }

    let created = 0;
    let skipped = 0;
    let errors = 0;
    const results: Array<{
      customer: string;
      category: string;
      amount: number;
      status: string;
      reason?: string;
    }> = [];

    for (const def of costDefinitions) {
      try {
        // Frekansa göre bu dönemde oluşturulmalı mı?
        if (!shouldChargeForPeriod(def.frequency, period, def.chargeStrategy)) {
          skipped++;
          results.push({
            customer: def.customers.unvan,
            category: def.category.name,
            amount: 0,
            status: "atlandı",
            reason: "Bu dönem için uygun frekans değil",
          });
          continue;
        }

        // Bu dönem için zaten oluşturulmuş mu?
        const existingLog = await prisma.auto_charge_logs.findUnique({
          where: {
            costDefinitionId_period: {
              costDefinitionId: def.id,
              period,
            },
          },
        });

        if (existingLog) {
          skipped++;
          results.push({
            customer: def.customers.unvan,
            category: def.category.name,
            amount: 0,
            status: "atlandı",
            reason: "Bu dönem için zaten oluşturulmuş",
          });
          continue;
        }

        // Tutar hesaplama
        const amounts = calculateAmounts(def);
        const dueDate = getLastDayOfMonth(now);

        // DEBIT transaction oluştur
        const transaction = await prisma.financial_transactions.create({
          data: {
            customerId: def.customerId,
            costDefinitionId: def.id,
            categoryId: def.categoryId,
            type: "DEBIT",
            amount: amounts.grossAmount,
            grossAmount: amounts.grossAmount,
            kdvAmount: amounts.kdvAmount,
            stopajAmount: amounts.stopajAmount,
            netAmount: amounts.netAmount,
            currency: def.currency,
            description: `${def.category.name} - ${period}`,
            date: now,
            dueDate,
            status: "PENDING",
            autoGenerated: true,
            tenantId: user.tenantId,
          },
        });

        // Log kaydı
        await prisma.auto_charge_logs.create({
          data: {
            costDefinitionId: def.id,
            transactionId: transaction.id,
            period,
            status: "SUCCESS",
            tenantId: user.tenantId,
          },
        });

        created++;
        results.push({
          customer: def.customers.unvan,
          category: def.category.name,
          amount: amounts.grossAmount,
          status: "oluşturuldu",
        });
      } catch (error) {
        errors++;
        results.push({
          customer: def.customers.unvan,
          category: def.category.name,
          amount: 0,
          status: "hata",
          reason: error instanceof Error ? error.message : "Bilinmeyen hata",
        });

        try {
          await prisma.auto_charge_logs.create({
            data: {
              costDefinitionId: def.id,
              period,
              status: "FAILED",
              errorMessage:
                error instanceof Error ? error.message : "Bilinmeyen hata",
              tenantId: user.tenantId,
            },
          });
        } catch {
          // Sessizce geç
        }
      }
    }

    return NextResponse.json({
      success: true,
      period,
      created,
      skipped,
      errors,
      total: costDefinitions.length,
      results,
    });
  } catch (error) {
    console.error("Manuel faturalama hatası:", error);
    return NextResponse.json({ error: "Sunucu hatası" }, { status: 500 });
  }
}

/**
 * GET /api/finance/auto-charge
 * Belirli bir dönem için faturalama durumunu kontrol et
 */
export async function GET(req: NextRequest) {
  try {
    const user = await getUserWithProfile();
    if (!user) {
      return NextResponse.json({ error: "Yetkisiz erişim" }, { status: 401 });
    }

    const { searchParams } = new URL(req.url);
    const period = searchParams.get("period") || getCurrentPeriod(new Date());

    // Bu dönem için log kayıtlarını getir
    const logs = await prisma.auto_charge_logs.findMany({
      where: {
        tenantId: user.tenantId,
        period,
      },
      include: {
        cost_definition: {
          include: {
            customers: { select: { unvan: true } },
            category: { select: { name: true } },
          },
        },
      },
      orderBy: { executedAt: "desc" },
    });

    // Aktif tanım sayısını getir
    const activeDefs = await prisma.cost_definitions.count({
      where: {
        tenantId: user.tenantId,
        isActive: true,
      },
    });

    return NextResponse.json({
      period,
      activeDefinitions: activeDefs,
      chargedCount: logs.filter((l) => l.status === "SUCCESS").length,
      failedCount: logs.filter((l) => l.status === "FAILED").length,
      logs: logs.map((l) => ({
        id: l.id,
        customer: l.cost_definition.customers.unvan,
        category: l.cost_definition.category.name,
        status: l.status,
        errorMessage: l.errorMessage,
        executedAt: l.executedAt,
      })),
    });
  } catch (error) {
    console.error("Faturalama durumu hatası:", error);
    return NextResponse.json({ error: "Sunucu hatası" }, { status: 500 });
  }
}

// ─── Yardımcı Fonksiyonlar ────────────────────────────────────────────

function getCurrentPeriod(date: Date): string {
  return `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, "0")}`;
}

function shouldChargeForPeriod(
  frequency: string,
  period: string,
  chargeStrategy: string
): boolean {
  const month = parseInt(period.split("-")[1], 10);

  switch (frequency) {
    case "MONTHLY":
      return true;
    case "QUARTERLY":
      if (chargeStrategy === "DISTRIBUTED") return true;
      return [1, 4, 7, 10].includes(month);
    case "BIANNUAL":
      if (chargeStrategy === "DISTRIBUTED") return true;
      return [1, 7].includes(month);
    case "ANNUAL":
      if (chargeStrategy === "DISTRIBUTED") return true;
      return month === 1;
    case "ONE_TIME":
      return false;
    default:
      return false;
  }
}

function toNum(val: unknown): number {
  if (val == null) return 0;
  if (typeof val === "number") return val;
  if (typeof val === "object" && val !== null && "toNumber" in val) {
    return (val as { toNumber: () => number }).toNumber();
  }
  return Number(val);
}

interface CostDefForCalc {
  amount: unknown;
  hasSMM: boolean;
  kdvRate: unknown;
  stopajRate: unknown;
  frequency: string;
  chargeStrategy: string;
}

function calculateAmounts(def: CostDefForCalc) {
  const baseAmount = toNum(def.amount);

  let periodAmount = baseAmount;
  if (def.chargeStrategy === "DISTRIBUTED") {
    switch (def.frequency) {
      case "ANNUAL":
        periodAmount = baseAmount / 12;
        break;
      case "BIANNUAL":
        periodAmount = baseAmount / 6;
        break;
      case "QUARTERLY":
        periodAmount = baseAmount / 3;
        break;
    }
  }

  const kdvRate = def.hasSMM ? toNum(def.kdvRate) : 0;
  const stopajRate = def.hasSMM ? toNum(def.stopajRate) : 0;

  const kdvAmount = periodAmount * (kdvRate / 100);
  const stopajAmount = periodAmount * (stopajRate / 100);
  const grossAmount = periodAmount + kdvAmount;
  const netAmount = periodAmount + kdvAmount - stopajAmount;

  return {
    grossAmount: Math.round(grossAmount * 100) / 100,
    kdvAmount: Math.round(kdvAmount * 100) / 100,
    stopajAmount: Math.round(stopajAmount * 100) / 100,
    netAmount: Math.round(netAmount * 100) / 100,
  };
}

function getLastDayOfMonth(date: Date): Date {
  return new Date(date.getFullYear(), date.getMonth() + 1, 0);
}
