import { getUserWithProfile } from "@/lib/supabase/auth";
import { prisma } from "@/lib/db";
import { NextRequest, NextResponse } from "next/server";

// İşlemleri listele
export async function GET(req: NextRequest) {
  try {
    const user = await getUserWithProfile();
    if (!user) {
      return NextResponse.json({ error: "Yetkisiz erişim" }, { status: 401 });
    }

    const { searchParams } = new URL(req.url);
    const customerId = searchParams.get("customerId");
    const type = searchParams.get("type"); // DEBIT veya CREDIT
    const status = searchParams.get("status");
    const categoryId = searchParams.get("categoryId");
    const startDate = searchParams.get("startDate");
    const endDate = searchParams.get("endDate");
    const page = parseInt(searchParams.get("page") || "1");
    const limit = parseInt(searchParams.get("limit") || "50");

    const where: Record<string, unknown> = { tenantId: user.tenantId };
    if (customerId) where.customerId = customerId;
    if (type === "DEBIT" || type === "CREDIT") where.type = type;
    if (status) where.status = status;
    if (categoryId) where.categoryId = categoryId;
    const autoGenerated = searchParams.get("autoGenerated");
    const hasCostDefinition = searchParams.get("hasCostDefinition");
    if (autoGenerated !== null) where.autoGenerated = autoGenerated === "true";
    if (hasCostDefinition === "false") where.costDefinitionId = null;
    if (hasCostDefinition === "true") where.costDefinitionId = { not: null };

    if (startDate || endDate) {
      where.date = {};
      if (startDate) (where.date as Record<string, unknown>).gte = new Date(startDate);
      if (endDate) (where.date as Record<string, unknown>).lte = new Date(endDate);
    }

    const [transactions, total] = await Promise.all([
      prisma.financial_transactions.findMany({
        where,
        include: {
          customers: { select: { id: true, unvan: true, kisaltma: true } },
          category: { select: { id: true, name: true, color: true, icon: true } },
          check: { select: { id: true, checkNumber: true, status: true, dueDate: true } },
        },
        orderBy: { date: "desc" },
        skip: (page - 1) * limit,
        take: limit,
      }),
      prisma.financial_transactions.count({ where }),
    ]);

    return NextResponse.json({
      data: transactions,
      total,
      page,
      limit,
      totalPages: Math.ceil(total / limit),
    });
  } catch (error) {
    console.error("İşlem listeleme hatası:", error);
    return NextResponse.json({ error: "Sunucu hatası" }, { status: 500 });
  }
}

// Yeni işlem oluştur
export async function POST(req: NextRequest) {
  try {
    const user = await getUserWithProfile();
    if (!user) {
      return NextResponse.json({ error: "Yetkisiz erişim" }, { status: 401 });
    }

    const body = await req.json();
    const {
      customerId, costDefinitionId, categoryId, type, amount, currency,
      exchangeRate, originalAmount, grossAmount, kdvAmount, stopajAmount,
      netAmount, description, date, dueDate, paymentMethod, status,
    } = body;

    if (!categoryId || !type || !amount || !netAmount || !date) {
      return NextResponse.json(
        { error: "Zorunlu alanlar eksik (kategori, tür, tutar, net tutar, tarih)" },
        { status: 400 }
      );
    }

    const transaction = await prisma.financial_transactions.create({
      data: {
        customerId: customerId || null,
        costDefinitionId: costDefinitionId || null,
        categoryId,
        type,
        amount,
        currency: currency || "TRY",
        exchangeRate: exchangeRate || null,
        originalAmount: originalAmount || null,
        grossAmount: grossAmount || null,
        kdvAmount: kdvAmount || null,
        stopajAmount: stopajAmount || null,
        netAmount,
        description: description || null,
        date: new Date(date),
        dueDate: dueDate ? new Date(dueDate) : null,
        paymentMethod: paymentMethod || null,
        status: status || "PENDING",
        tenantId: user.tenantId,
      },
      include: {
        customers: { select: { id: true, unvan: true, kisaltma: true } },
        category: { select: { id: true, name: true, color: true } },
      },
    });

    return NextResponse.json(transaction, { status: 201 });
  } catch (error) {
    console.error("İşlem oluşturma hatası:", error);
    return NextResponse.json({ error: "Sunucu hatası" }, { status: 500 });
  }
}
